// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PbPacket.proto

package com.keimons.eoc.protobuf;

public final class PbPacket {
  private PbPacket() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.keimons.eoc.protobuf.Packet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 消息号
     * </pre>
     *
     * <code>int32 msgCode = 1;</code>
     */
    int getMsgCode();

    /**
     * <pre>
     * 错误号
     * </pre>
     *
     * <code>repeated string errCode = 2;</code>
     */
    java.util.List<String>
        getErrCodeList();
    /**
     * <pre>
     * 错误号
     * </pre>
     *
     * <code>repeated string errCode = 2;</code>
     */
    int getErrCodeCount();
    /**
     * <pre>
     * 错误号
     * </pre>
     *
     * <code>repeated string errCode = 2;</code>
     */
    String getErrCode(int index);
    /**
     * <pre>
     * 错误号
     * </pre>
     *
     * <code>repeated string errCode = 2;</code>
     */
    com.google.protobuf.ByteString
        getErrCodeBytes(int index);

    /**
     * <pre>
     * 消息体
     * </pre>
     *
     * <code>bytes data = 3;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code com.keimons.eoc.protobuf.Packet}
   */
  public  static final class Packet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.keimons.eoc.protobuf.Packet)
      PacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Packet.newBuilder() to construct.
    private Packet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Packet() {
      msgCode_ = 0;
      errCode_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Packet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              msgCode_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                errCode_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              errCode_.add(s);
              break;
            }
            case 26: {

              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          errCode_ = errCode_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.keimons.eoc.protobuf.PbPacket.internal_static_com_keimons_eoc_protobuf_Packet_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.keimons.eoc.protobuf.PbPacket.internal_static_com_keimons_eoc_protobuf_Packet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.keimons.eoc.protobuf.PbPacket.Packet.class, com.keimons.eoc.protobuf.PbPacket.Packet.Builder.class);
    }

    private int bitField0_;
    public static final int MSGCODE_FIELD_NUMBER = 1;
    private int msgCode_;
    /**
     * <pre>
     * 消息号
     * </pre>
     *
     * <code>int32 msgCode = 1;</code>
     */
    public int getMsgCode() {
      return msgCode_;
    }

    public static final int ERRCODE_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList errCode_;
    /**
     * <pre>
     * 错误号
     * </pre>
     *
     * <code>repeated string errCode = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getErrCodeList() {
      return errCode_;
    }
    /**
     * <pre>
     * 错误号
     * </pre>
     *
     * <code>repeated string errCode = 2;</code>
     */
    public int getErrCodeCount() {
      return errCode_.size();
    }
    /**
     * <pre>
     * 错误号
     * </pre>
     *
     * <code>repeated string errCode = 2;</code>
     */
    public String getErrCode(int index) {
      return errCode_.get(index);
    }
    /**
     * <pre>
     * 错误号
     * </pre>
     *
     * <code>repeated string errCode = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrCodeBytes(int index) {
      return errCode_.getByteString(index);
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString data_;
    /**
     * <pre>
     * 消息体
     * </pre>
     *
     * <code>bytes data = 3;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgCode_ != 0) {
        output.writeInt32(1, msgCode_);
      }
      for (int i = 0; i < errCode_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errCode_.getRaw(i));
      }
      if (!data_.isEmpty()) {
        output.writeBytes(3, data_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, msgCode_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < errCode_.size(); i++) {
          dataSize += computeStringSizeNoTag(errCode_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getErrCodeList().size();
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.keimons.eoc.protobuf.PbPacket.Packet)) {
        return super.equals(obj);
      }
      com.keimons.eoc.protobuf.PbPacket.Packet other = (com.keimons.eoc.protobuf.PbPacket.Packet) obj;

      boolean result = true;
      result = result && (getMsgCode()
          == other.getMsgCode());
      result = result && getErrCodeList()
          .equals(other.getErrCodeList());
      result = result && getData()
          .equals(other.getData());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSGCODE_FIELD_NUMBER;
      hash = (53 * hash) + getMsgCode();
      if (getErrCodeCount() > 0) {
        hash = (37 * hash) + ERRCODE_FIELD_NUMBER;
        hash = (53 * hash) + getErrCodeList().hashCode();
      }
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.keimons.eoc.protobuf.PbPacket.Packet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.keimons.eoc.protobuf.PbPacket.Packet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.keimons.eoc.protobuf.PbPacket.Packet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.keimons.eoc.protobuf.PbPacket.Packet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.keimons.eoc.protobuf.PbPacket.Packet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.keimons.eoc.protobuf.PbPacket.Packet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.keimons.eoc.protobuf.PbPacket.Packet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.keimons.eoc.protobuf.PbPacket.Packet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.keimons.eoc.protobuf.PbPacket.Packet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.keimons.eoc.protobuf.PbPacket.Packet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.keimons.eoc.protobuf.PbPacket.Packet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.keimons.eoc.protobuf.PbPacket.Packet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.keimons.eoc.protobuf.PbPacket.Packet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.keimons.eoc.protobuf.Packet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.keimons.eoc.protobuf.Packet)
        com.keimons.eoc.protobuf.PbPacket.PacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.keimons.eoc.protobuf.PbPacket.internal_static_com_keimons_eoc_protobuf_Packet_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.keimons.eoc.protobuf.PbPacket.internal_static_com_keimons_eoc_protobuf_Packet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.keimons.eoc.protobuf.PbPacket.Packet.class, com.keimons.eoc.protobuf.PbPacket.Packet.Builder.class);
      }

      // Construct using com.keimons.eoc.protobuf.PbPacket.Packet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        msgCode_ = 0;

        errCode_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.keimons.eoc.protobuf.PbPacket.internal_static_com_keimons_eoc_protobuf_Packet_descriptor;
      }

      public com.keimons.eoc.protobuf.PbPacket.Packet getDefaultInstanceForType() {
        return com.keimons.eoc.protobuf.PbPacket.Packet.getDefaultInstance();
      }

      public com.keimons.eoc.protobuf.PbPacket.Packet build() {
        com.keimons.eoc.protobuf.PbPacket.Packet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.keimons.eoc.protobuf.PbPacket.Packet buildPartial() {
        com.keimons.eoc.protobuf.PbPacket.Packet result = new com.keimons.eoc.protobuf.PbPacket.Packet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.msgCode_ = msgCode_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          errCode_ = errCode_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.errCode_ = errCode_;
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.keimons.eoc.protobuf.PbPacket.Packet) {
          return mergeFrom((com.keimons.eoc.protobuf.PbPacket.Packet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.keimons.eoc.protobuf.PbPacket.Packet other) {
        if (other == com.keimons.eoc.protobuf.PbPacket.Packet.getDefaultInstance()) return this;
        if (other.getMsgCode() != 0) {
          setMsgCode(other.getMsgCode());
        }
        if (!other.errCode_.isEmpty()) {
          if (errCode_.isEmpty()) {
            errCode_ = other.errCode_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureErrCodeIsMutable();
            errCode_.addAll(other.errCode_);
          }
          onChanged();
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.keimons.eoc.protobuf.PbPacket.Packet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.keimons.eoc.protobuf.PbPacket.Packet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int msgCode_ ;
      /**
       * <pre>
       * 消息号
       * </pre>
       *
       * <code>int32 msgCode = 1;</code>
       */
      public int getMsgCode() {
        return msgCode_;
      }
      /**
       * <pre>
       * 消息号
       * </pre>
       *
       * <code>int32 msgCode = 1;</code>
       */
      public Builder setMsgCode(int value) {
        
        msgCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息号
       * </pre>
       *
       * <code>int32 msgCode = 1;</code>
       */
      public Builder clearMsgCode() {
        
        msgCode_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList errCode_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureErrCodeIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          errCode_ = new com.google.protobuf.LazyStringArrayList(errCode_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <pre>
       * 错误号
       * </pre>
       *
       * <code>repeated string errCode = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getErrCodeList() {
        return errCode_.getUnmodifiableView();
      }
      /**
       * <pre>
       * 错误号
       * </pre>
       *
       * <code>repeated string errCode = 2;</code>
       */
      public int getErrCodeCount() {
        return errCode_.size();
      }
      /**
       * <pre>
       * 错误号
       * </pre>
       *
       * <code>repeated string errCode = 2;</code>
       */
      public String getErrCode(int index) {
        return errCode_.get(index);
      }
      /**
       * <pre>
       * 错误号
       * </pre>
       *
       * <code>repeated string errCode = 2;</code>
       */
      public com.google.protobuf.ByteString
          getErrCodeBytes(int index) {
        return errCode_.getByteString(index);
      }
      /**
       * <pre>
       * 错误号
       * </pre>
       *
       * <code>repeated string errCode = 2;</code>
       */
      public Builder setErrCode(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureErrCodeIsMutable();
        errCode_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 错误号
       * </pre>
       *
       * <code>repeated string errCode = 2;</code>
       */
      public Builder addErrCode(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureErrCodeIsMutable();
        errCode_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 错误号
       * </pre>
       *
       * <code>repeated string errCode = 2;</code>
       */
      public Builder addAllErrCode(
          Iterable<String> values) {
        ensureErrCodeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, errCode_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 错误号
       * </pre>
       *
       * <code>repeated string errCode = 2;</code>
       */
      public Builder clearErrCode() {
        errCode_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 错误号
       * </pre>
       *
       * <code>repeated string errCode = 2;</code>
       */
      public Builder addErrCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureErrCodeIsMutable();
        errCode_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * 消息体
       * </pre>
       *
       * <code>bytes data = 3;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <pre>
       * 消息体
       * </pre>
       *
       * <code>bytes data = 3;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息体
       * </pre>
       *
       * <code>bytes data = 3;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.keimons.eoc.protobuf.Packet)
    }

    // @@protoc_insertion_point(class_scope:com.keimons.eoc.protobuf.Packet)
    private static final com.keimons.eoc.protobuf.PbPacket.Packet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.keimons.eoc.protobuf.PbPacket.Packet();
    }

    public static com.keimons.eoc.protobuf.PbPacket.Packet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Packet>
        PARSER = new com.google.protobuf.AbstractParser<Packet>() {
      public Packet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Packet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Packet> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Packet> getParserForType() {
      return PARSER;
    }

    public com.keimons.eoc.protobuf.PbPacket.Packet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_keimons_eoc_protobuf_Packet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_keimons_eoc_protobuf_Packet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016PbPacket.proto\022\030com.keimons.eoc.protob" +
      "uf\"8\n\006Packet\022\017\n\007msgCode\030\001 \001(\005\022\017\n\007errCode" +
      "\030\002 \003(\t\022\014\n\004data\030\003 \001(\014b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_keimons_eoc_protobuf_Packet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_keimons_eoc_protobuf_Packet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_keimons_eoc_protobuf_Packet_descriptor,
        new String[] { "MsgCode", "ErrCode", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
